/**
 * This file is auto-generated by GenerateModulesWebpackPlugin.
 * Check this file into source control.
 * Do not edit this file.
 */
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _vite = require("vite");

var _pluginVue = _interopRequireDefault(require("@vitejs/plugin-vue"));

var _vitePluginDts = _interopRequireDefault(require("vite-plugin-dts"));

var _path = require("path");

var _vitePluginGenerateExports = _interopRequireDefault(require("@packages/vite-plugin-generate-exports"));

var _vitePluginGenerateModules = _interopRequireDefault(require("@packages/vite-plugin-generate-modules"));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

const mode = (() => {
  const args = process.argv;
  const index = args.indexOf('--mode');
  return index < 0 ? 'production' : args[index + 1];
})();

const name = 'ui'; // https://vitejs.dev/config/

var _default = (0, _vite.defineConfig)({
  plugins: [(0, _pluginVue.default)(), (0, _vitePluginDts.default)(), (0, _vitePluginGenerateExports.default)({
    watch: mode === 'development',
    entries: [{
      omitExtension: false,
      omitSemi: true,
      filename: 'index.ts',
      include: ['**/*.vue'],
      exclude: ['**/Icons/*'],
      directories: ['./src/components']
    }, {
      omitExtension: false,
      omitSemi: true,
      filename: 'index.ts',
      include: ['**/*.vue'],
      exclude: ['**/*Story.vue'],
      directories: ['./src/components/typography/Icons']
    }]
  }), (0, _vitePluginGenerateModules.default)({
    watch: mode === 'development',
    entries: [{
      pattern: './src/styles/tokens.ts',
      into: ['commonjs']
    }, {
      pattern: './vite.config.ts',
      into: ['commonjs']
    }]
  })],
  resolve: {
    alias: {
      '@': (0, _path.resolve)(__dirname, 'src')
    }
  },
  build: {
    lib: {
      entry: (0, _path.resolve)(__dirname, 'src/main.ts'),
      name: name,
      formats: ['cjs', 'es'],
      fileName: format => `${name}.${{
        cjs: 'cjs',
        es: 'es.js'
      }[format]}`
    },
    rollupOptions: {
      external: ['vue']
    }
  }
});

exports.default = _default;
/* End of auto-generated content. */
