/**
 * This file is auto-generated by GenerateExportsWebpackPlugin.
 * Check this file into source control.
 * Do not edit this file.
 */
export { default as useMediaDevices } from './useMediaDevices'
/* End of auto-generated content. */
